"""
End-to-end smoke test on SYNTHETIC data.

This script exists to satisfy two things at once: (1) a runnable
demonstration that every module wired together actually produces numbers,
and (2) the M3 requirement to "submit initial findings and temporary
results." Read the second part of that sentence carefully: these are
temporary results on synthetic 2-regime data, generated by
data.make_synthetic_universe -- NOT a claim about the real ten-ETF
universe. Real ETF price data has not been pulled into this repository
(this development sandbox has no network access), so there is nothing
here yet that speaks to the actual research questions. Re-run this same
script against real data (see data.PriceDataset.from_csv_dir) once it is
available, and the comparison becomes real.

What this DOES demonstrate honestly, on synthetic data with genuine
(simulated) regimes:
  - the HMM recovers the simulated states with high accuracy (see
    tests/test_regime.py for the quantified check)
  - M1 (regime-aware) out-predicts M0 (pooled) in log-likelihood, i.e.
    there is something for the reliability layer to detect
  - the ERC baseline/regime/reliability-blend configurations run
    end-to-end through the shared constraint-projection layer and
    produce genuinely different weight paths and turnover

Usage:
    python scripts/run_smoke_test.py
"""

import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from data import make_synthetic_universe  # noqa: E402
from walkforward import run_walk_forward  # noqa: E402
from constraints import ConstraintSpec, drift_weights  # noqa: E402
from evaluation import (  # noqa: E402
    sharpe_ratio, cagr, max_drawdown, sortino_ratio, calmar_ratio,
    herfindahl_concentration, average_turnover, block_bootstrap_diff_ci,
)


def main() -> None:
    print("=" * 78)
    print("SMOKE TEST -- synthetic 2-regime data, NOT the real ten-ETF universe")
    print("=" * 78)

    ds, true_state = make_synthetic_universe(n_days=900, seed=7)
    returns = ds.returns

    t0 = time.time()
    result = run_walk_forward(
        returns,
        n_states=2,
        initial_window=252,
        alpha=0.97,
        constraint_spec=ConstraintSpec(lower=0.0, upper=0.30, max_turnover=0.30),
    )
    runtime = time.time() - t0
    print(f"\nWalk-forward runtime: {runtime:.1f}s over {len(result.dates)} trading days\n")

    rows = []
    for config, r in result.portfolio_returns.items():
        w = result.weights[config]
        w_drift = np.array([
            drift_weights(w[i - 1] if i > 0 else w[0], np.exp(returns.to_numpy()[251 + i]))
            for i in range(len(w))
        ])
        rows.append({
            "config": config,
            "sharpe": round(sharpe_ratio(r), 3),
            "cagr": round(cagr(r), 4),
            "max_drawdown": round(max_drawdown(r), 4),
            "sortino": round(sortino_ratio(r), 3),
            "calmar": round(calmar_ratio(r), 3),
            "avg_turnover": round(average_turnover(w, w_drift), 4),
            "concentration_hhi": round(herfindahl_concentration(w), 4),
        })
    summary = pd.DataFrame(rows).set_index("config")
    print(summary.to_string())

    print("\n--- Paired block-bootstrap: erc_blend vs erc_baseline (Sharpe difference) ---")
    ci = block_bootstrap_diff_ci(
        result.portfolio_returns["erc_blend"],
        result.portfolio_returns["erc_baseline"],
        n_boot=1000, random_state=0,
    )
    print(f"point estimate: {ci['point_estimate']:.3f}, "
          f"{int(ci['ci_level']*100)}% CI: [{ci['ci_low']:.3f}, {ci['ci_high']:.3f}]")

    print("\n--- Reliability path pi_t ---")
    pi = np.array(result.pi_history)
    print(f"mean pi_t: {pi.mean():.3f}  min: {pi.min():.3f}  max: {pi.max():.3f}")

    out_dir = Path(__file__).resolve().parents[1] / "outputs"
    out_dir.mkdir(exist_ok=True)
    summary.to_csv(out_dir / "smoke_test_summary.csv")
    pd.Series(result.pi_history, index=result.dates, name="pi_t").to_csv(out_dir / "smoke_test_pi_path.csv")
    print(f"\nSaved summary to {out_dir / 'smoke_test_summary.csv'}")
    print("\nReminder: synthetic data. Re-run against real ETF data before citing any of this in M3/M4.")


if __name__ == "__main__":
    main()
